/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GuidesFreeMedicalEquipmentRouteImport } from './routes/guides.free-medical-equipment'
import { Route as GuidesDonateSuppliesRouteImport } from './routes/guides.donate-supplies'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const GuidesFreeMedicalEquipmentRoute =
  GuidesFreeMedicalEquipmentRouteImport.update({
    id: '/guides/free-medical-equipment',
    path: '/guides/free-medical-equipment',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesDonateSuppliesRoute = GuidesDonateSuppliesRouteImport.update({
  id: '/guides/donate-supplies',
  path: '/guides/donate-supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/request': typeof RequestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/guides/donate-supplies': typeof GuidesDonateSuppliesRoute
  '/guides/free-medical-equipment': typeof GuidesFreeMedicalEquipmentRoute
  '/news/$slug': typeof NewsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/request': typeof RequestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/guides/donate-supplies': typeof GuidesDonateSuppliesRoute
  '/guides/free-medical-equipment': typeof GuidesFreeMedicalEquipmentRoute
  '/news/$slug': typeof NewsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/request': typeof RequestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/guides/donate-supplies': typeof GuidesDonateSuppliesRoute
  '/guides/free-medical-equipment': typeof GuidesFreeMedicalEquipmentRoute
  '/news/$slug': typeof NewsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/donate'
    | '/gallery'
    | '/get-involved'
    | '/news'
    | '/programs'
    | '/request'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/register'
    | '/guides/donate-supplies'
    | '/guides/free-medical-equipment'
    | '/news/$slug'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/donate'
    | '/gallery'
    | '/get-involved'
    | '/news'
    | '/programs'
    | '/request'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/register'
    | '/guides/donate-supplies'
    | '/guides/free-medical-equipment'
    | '/news/$slug'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/donate'
    | '/gallery'
    | '/get-involved'
    | '/news'
    | '/programs'
    | '/request'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/register'
    | '/guides/donate-supplies'
    | '/guides/free-medical-equipment'
    | '/news/$slug'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  RequestRoute: typeof RequestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  GuidesDonateSuppliesRoute: typeof GuidesDonateSuppliesRoute
  GuidesFreeMedicalEquipmentRoute: typeof GuidesFreeMedicalEquipmentRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/guides/free-medical-equipment': {
      id: '/guides/free-medical-equipment'
      path: '/guides/free-medical-equipment'
      fullPath: '/guides/free-medical-equipment'
      preLoaderRoute: typeof GuidesFreeMedicalEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/donate-supplies': {
      id: '/guides/donate-supplies'
      path: '/guides/donate-supplies'
      fullPath: '/guides/donate-supplies'
      preLoaderRoute: typeof GuidesDonateSuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  NewsRoute: NewsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  RequestRoute: RequestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  GuidesDonateSuppliesRoute: GuidesDonateSuppliesRoute,
  GuidesFreeMedicalEquipmentRoute: GuidesFreeMedicalEquipmentRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
